### ISSUE TITLE
Bug in OAS shrinkage formula

### ISSUE THREAD

**Issue by rmcgibbo** [AEBilgrau/correlateR#4]
The OAS shrinkage formula does not properly follow the equations written in the referenced paper. https://github.com/AEBilgrau/correlateR/blob/master/R/Scov.R#L81-L82. Note that the parenthesis are misplaced with respect to `(1 - 2)/p` vs. `(1-2/p)` in the numerator, and a similar thing in the denominator.

**Comment by AEBilgrau** [comment]
Thank you very much. I'll investigate ASAP and update the package.

**Comment by rmcgibbo** [comment]
Unfortunately, I couldn't get much of the paper to work out at all -- e.g. eqs. 23 and 30 are supposed to be two equations for the same thing, but are clearly not equivalent, and eqs. 24/25 claimed to be algebraic simplifications that are equivalent to eqs 20/21, but I don't think that is correct either.

**Comment by AEBilgrau** [comment]
Thanks, @rmcgibbo. I took a (regrettably only quick) look into the issue based on your second comment.  But all I managed was to agree that something seems fishy. Hopefully, I'll get around it again not too soon to solve the issue satisfactorily. Or maybe one should contact the authors?
